import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/drizzle/**',
      // Generated by `pnpm contract:generate`, and held by its own drift test (P5a Decision 9).
      'packages/contract/src/schema.d.ts',
    ],
  },
  ...tseslint.configs.recommended,
  {
    files: ['packages/control-plane/src/**/*.ts'],
    rules: {
      // An underscore prefix is the project's "deliberately unused" marker. The
      // Driver interface fixes several signatures that an implementation may not
      // need in full — the fake driver's `exec(id, cmd, _opts)` is the first —
      // and without this the rule fires on faithfully implementing the interface.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // §5's module boundary is enforced by src/module-boundaries.test.ts, NOT here.
      //
      // `no-restricted-imports` matches its `group` globs with gitignore semantics,
      // and that dialect cannot express this rule. Measured 2026-09-05: a ban wide
      // enough to catch `../db/schema.js` — say `../*/*` — also matches the
      // DIRECTORY `../../identity`, and gitignore cannot re-include a file whose
      // parent directory is excluded. So `!../../*/index.js` is unreachable and a
      // legitimate `api/routes/auth.ts -> ../../identity/index.js` is reported as a
      // violation. Every arrangement of bans and negations tried had the same hole:
      // the two are the same pattern at different depths.
      //
      // This is the second defect this one rule has produced (the first: ESLint 9's
      // globs have no extglob, so `!(index)` matched nothing). The test resolves
      // each import and compares the modules the two files belong to, which is
      // correct at any depth and is what self-review defect 7 fixed it to do.
      // Verified by pointing api/routes/auth.ts at ../../identity/session.js and
      // watching the test name both violations.
      //
      // If a lint-time check is wanted back, it needs a rule that understands paths
      // rather than globs — eslint-plugin-import's `no-restricted-paths` zones.
    },
  },
  {
    // §22 and §16 API completeness (P5a Task 7): the journey is a client of the contract
    // and may import nothing else. The TEST in packages/journey/src/boundary.test.ts is the
    // other half; each was watched failing. `regex`, not `group`: the gitignore dialect
    // cannot say "only these" (see the control plane's note above).
    files: ['packages/journey/src/**/*.ts'],
    ignores: ['packages/journey/src/**/*.test.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              regex: '^(?!@manifest/contract$|node:|\\./)',
              message:
                'The journey may import only @manifest/contract, node: builtins and its own ./ files (§22).',
            },
          ],
        },
      ],
    },
  },
  {
    // §22 and §16 API completeness (D22, P5c Task 3): the console is a client of the
    // contract and may import nothing else — plus React, which renders it, and its own
    // files. The TEST in packages/console/src/boundary.test.ts is the other half, and it
    // covers what a lint rule cannot: a `fetch` that reaches the API without importing
    // anything at all. Each was watched failing.
    //
    // `regex`, not `group`: ESLint 9's gitignore dialect cannot say "only these" — the
    // control plane's module-boundary note above has the measurement.
    //
    // vite.config.ts is deliberately outside these globs: it is the build's own
    // configuration, not the client, and it imports vite and @vitejs/plugin-react.
    //
    // `\\.{1,2}/` — BOTH `./` and `../`, widened in Task 5 (P5c sitting 4), which wrote
    // the console's first subdirectory. `src/screens/projects.tsx` imports `../api`, and
    // with `\\./` alone every one of those was an error while the boundary TEST — which
    // has allowed `./` and `../` since Task 3 — was green. The two halves of one rule
    // disagreed, and the test was the half that was right.
    //
    // This half cannot be more precise than that: a regex over a specifier cannot tell
    // `../api` from `../../control-plane/src/db/index.js`. The TEST resolves each relative
    // specifier and requires the target to land under packages/console/src, which is the
    // containment check, and it is watched failing.
    files: ['packages/console/src/**/*.ts', 'packages/console/src/**/*.tsx'],
    ignores: ['packages/console/src/**/*.test.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              regex: '^(?!@manifest/contract$|react$|react-dom(/.*)?$|node:|\\.{1,2}/)',
              message:
                'The console may import only @manifest/contract, react, react-dom, node: builtins and its own ./ files (D22, §22).',
            },
          ],
        },
      ],
    },
  },
)
