import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { JOURNEY } from './coverage.js'

/**
 * `pnpm docs:write` — THE GUIDES' GENERATED HALF (the authoring API plan's Task 11, Decisions 16
 * and 19). It fills every `<!-- example: <file> -->` span in a hand-written page with that file's
 * text, so a guide's code is a file `pnpm typecheck` compiles and `examples.test.ts` runs; writes
 * the four reference pages from the published OpenAPI document; writes `journey.md`'s and
 * `events.md`'s tables between their markers; and writes `llms.txt`, with its copy in the
 * console's `public/`. `docs.test.ts` runs `generateDocs` into memory and compares every file with
 * what is committed, so a page older than the document or an example is red.
 *
 * Plain Node, run by type stripping: no enums, no parameter properties.
 */
const REPO = fileURLToPath(new URL('../../../', import.meta.url))
export const DOCS_DIR = join(REPO, 'docs', 'api')
const DOCUMENT = join(REPO, 'packages', 'contract', 'openapi.json')
const EXAMPLES_DIR = fileURLToPath(new URL('.', import.meta.url))
export const LLMS_COPY = join(REPO, 'packages', 'console', 'public', 'llms.txt')

type Json = Record<string, unknown>

interface Operation {
  operationId: string
  method: string
  path: string
  tag: string
  summary: string
  description: string
  sessionOnly: boolean
  parameters: { name: string; in: string; required: boolean; description: string }[]
  request: unknown
  success: { status: string; example: unknown } | undefined
  errors: string[]
  websocket: boolean
}

interface ErrorEntry {
  status: number
  summary: string
  remedy: string
}

interface EventType {
  type: string
  description: string
  example: unknown
}

const METHODS = ['get', 'post', 'put', 'patch', 'delete'] as const

function operationsOf(document: Json): Operation[] {
  const out: Operation[] = []
  for (const [path, item] of Object.entries(document.paths as Record<string, Json>)) {
    for (const method of METHODS) {
      const op = item[method] as Json | undefined
      if (op === undefined) continue
      const responses = (op.responses ?? {}) as Record<string, Json>
      const status = Object.keys(responses).find((s) => /^2\d\d$/.test(s))
      const json = (status === undefined ? undefined : responses[status]?.content) as
        Record<string, Json> | undefined
      const body = (op.requestBody as Json | undefined)?.content as
        Record<string, Json> | undefined
      const security = op.security as Json[] | undefined
      out.push({
        operationId: op.operationId as string,
        method: method.toUpperCase(),
        path,
        tag: (op.tags as string[])[0]!,
        summary: op.summary as string,
        description: op.description as string,
        sessionOnly:
          security !== undefined && security.length === 1 && 'session' in security[0]!,
        parameters: ((op.parameters ?? []) as Json[])
          .filter((p) => p.in !== 'header')
          .map((p) => ({
            name: p.name as string,
            in: p.in as string,
            required: p.required === true,
            description: (p.description as string | undefined) ?? '',
          })),
        request: body?.['application/json']?.example,
        success:
          status === undefined
            ? undefined
            : { status, example: json?.['application/json']?.example },
        errors: (op['x-manifest-error-codes'] ?? []) as string[],
        websocket: op['x-manifest-websocket'] !== undefined,
      })
    }
  }
  return out
}

/** A table cell: one line, pipes escaped. */
const cell = (text: string): string => text.replace(/\|/g, '\\|').replace(/\n+/g, ' ')

const json = (value: unknown): string =>
  ['```json', JSON.stringify(value, null, 2), '```'].join('\n')

const GENERATED = (from: string) =>
  `<!-- GENERATED by \`pnpm docs:write\` from ${from}. Do not edit: change the source and run it again. -->`

function operationsPage(document: Json): string {
  const ops = operationsOf(document)
  const errors = document['x-manifest-errors'] as Record<string, ErrorEntry>
  const tags = (document.tags as { name: string; description?: string }[]).filter((t) =>
    ops.some((o) => o.tag === t.name),
  )
  const lines: string[] = [
    '# Operations',
    '',
    GENERATED('the OpenAPI document'),
    `Every operation of Manifest’s API, version ${(document.info as Json).version as string}, grouped by what it is about: its method and path, who may call it, its parameters, an example of what it sends and answers, and every error code it can answer with what to do about each. Generated from the OpenAPI document (\`GET /v1/openapi.json\`), so it is exactly what the API does.`,
    '',
  ]
  for (const tag of tags) {
    lines.push(`## ${tag.name}`, '')
    if (tag.description !== undefined) lines.push(tag.description, '')
    for (const op of ops.filter((o) => o.tag === tag.name)) {
      lines.push(`### \`${op.operationId}\` — ${op.summary}`, '')
      lines.push(
        `\`${op.method} ${op.path}\`${op.websocket ? ' — a WebSocket upgrade' : ''} · ${
          op.sessionOnly
            ? 'a session only — a delegated token is refused'
            : 'a session or a delegated token'
        }`,
        '',
      )
      lines.push(op.description, '')
      if (op.parameters.length > 0) {
        lines.push('| Parameter | In | Required | What it is |', '|---|---|---|---|')
        for (const p of op.parameters)
          lines.push(
            `| \`${p.name}\` | ${p.in} | ${p.required ? 'yes' : 'no'} | ${cell(p.description)} |`,
          )
        lines.push('')
      }
      if (op.request !== undefined) lines.push('Request:', '', json(op.request), '')
      if (op.success?.example !== undefined)
        lines.push(`Answer, \`${op.success.status}\`:`, '', json(op.success.example), '')
      if (op.errors.length > 0) {
        lines.push('| Error | Status | What to do |', '|---|---|---|')
        for (const code of op.errors) {
          const entry = errors[code]
          lines.push(
            `| \`${code}\` | ${entry?.status ?? ''} | ${cell(entry?.remedy ?? '')} |`,
          )
        }
        lines.push('')
      }
    }
  }
  return lines.join('\n')
}

function errorsPage(document: Json): string {
  const errors = document['x-manifest-errors'] as Record<string, ErrorEntry>
  const spec = document['x-manifest-spec-errors'] as Record<
    string,
    { summary: string; remedy: string }
  >
  const lines = [
    '# Error codes',
    '',
    GENERATED('the OpenAPI document’s `x-manifest-errors` and `x-manifest-spec-errors`'),
    'Every code the API answers in its error envelope, with the status it always comes with, what it means and what to do next — and every code a `SPEC_INVALID` answer lists in `details`, one per problem in manifest.yaml. A client switches on the code and never on the message.',
    '',
    '## In the envelope',
    '',
    '| Code | Status | What it means | What to do |',
    '|---|---|---|---|',
  ]
  for (const [code, e] of Object.entries(errors).sort(([a], [b]) => (a < b ? -1 : 1)))
    lines.push(`| \`${code}\` | ${e.status} | ${cell(e.summary)} | ${cell(e.remedy)} |`)
  lines.push(
    '',
    '## Inside `details`, for `SPEC_INVALID`',
    '',
    'Each problem carries its own `path` in manifest.yaml, a `message` naming the values, and a `hint`; the code names the rule.',
    '',
    '| Code | What it means | What to do |',
    '|---|---|---|',
  )
  for (const [code, e] of Object.entries(spec).sort(([a], [b]) => (a < b ? -1 : 1)))
    lines.push(`| \`${code}\` | ${cell(e.summary)} | ${cell(e.remedy)} |`)
  lines.push('')
  return lines.join('\n')
}

function eventTypesOf(document: Json): EventType[] {
  const paths = document.paths as Record<string, Record<string, Json>>
  const stream = paths['/v1/projects/{projectId}/events']?.get
  return (stream?.['x-manifest-event-types'] ?? []) as EventType[]
}

function eventsReferencePage(document: Json): string {
  const lines = [
    '# Event types',
    '',
    GENERATED('the OpenAPI document’s `x-manifest-event-types`'),
    'Every event the project’s stream carries, in the order the platform defines them: what each says happened, and an example of its `machineDetail`. An event is also a line in the project’s audit trail, which nothing can change or remove.',
    '',
  ]
  for (const e of eventTypesOf(document))
    lines.push(`## \`${e.type}\``, '', e.description, '', json(e.example), '')
  return lines.join('\n')
}

interface Field {
  path: string
  type: string
  required: boolean
  description: string
  default?: unknown
}

function typeOf(schema: Json): string {
  if (schema.not !== undefined) return 'forbidden'
  if (Array.isArray(schema.enum))
    return (schema.enum as unknown[]).map((v) => `\`${String(v)}\``).join(', ')
  if (schema.const !== undefined) return `\`${String(schema.const)}\``
  if (Array.isArray(schema.type)) return (schema.type as string[]).join(' or ')
  if (typeof schema.type === 'string') {
    if (schema.type === 'array') {
      const items = schema.items as Json | undefined
      return items === undefined ? 'list' : `list of ${typeOf(items)}`
    }
    return schema.type
  }
  if (Array.isArray(schema.anyOf))
    return (schema.anyOf as Json[]).map(typeOf).join(' or ')
  return 'any'
}

function fieldsOf(schema: Json, prefix: string, out: Field[]): void {
  const properties = (schema.properties ?? {}) as Record<string, Json>
  const required = new Set((schema.required ?? []) as string[])
  for (const [name, child] of Object.entries(properties)) {
    const path = prefix === '' ? name : `${prefix}.${name}`
    out.push({
      path,
      type: typeOf(child),
      required: required.has(name),
      description: (child.description as string | undefined) ?? '',
      ...('default' in child ? { default: child.default } : {}),
    })
    if (child.type === 'object') fieldsOf(child, path, out)
    const items = child.items as Json | undefined
    if (child.type === 'array' && items?.type === 'object')
      fieldsOf(items, `${path}[]`, out)
  }
}

function manifestYamlPage(document: Json): string {
  const schema = (document.components as Json).schemas as Record<string, Json>
  const manifest = schema.ManifestYaml!
  const fields: Field[] = []
  fieldsOf(manifest, '', fields)
  const lines = [
    '# manifest.yaml',
    '',
    GENERATED('the OpenAPI document’s `ManifestYaml` schema'),
    'Every field an app’s manifest.yaml may declare, as a table: its path, its type, whether it is required, its default, and what it means. It is documentation for the file; the platform validates with its own code, and some rules are not expressible here — see the end of this page.',
    '',
    '| Field | Type | Required | Default | What it is |',
    '|---|---|---|---|---|',
  ]
  for (const f of fields)
    lines.push(
      `| \`${f.path}\` | ${cell(f.type)} | ${f.required ? 'yes' : 'no'} | ${
        f.default === undefined ? '' : `\`${cell(JSON.stringify(f.default))}\``
      } | ${cell(f.description)} |`,
    )
  lines.push('', '## What the table cannot say', '', manifest.description as string, '')
  return lines.join('\n')
}

/** `journey.md`'s table, from `JOURNEY` — every step, the operations that serve it, or its plan. */
function journeyTable(): string {
  const lines = ['| Step | Who | Operations |', '|---|---|---|']
  for (const s of JOURNEY)
    lines.push(
      `| ${cell(s.step)} | ${s.who} | ${
        s.later === undefined
          ? s.operations.map((o) => `\`${o}\``).join(', ')
          : `*Not yet — ${cell(s.later.plan)}:* ${cell(s.later.why)}`
      } |`,
    )
  return lines.join('\n')
}

/** `events.md`'s table: every type and the one sentence that says what happened. */
function eventTypesTable(document: Json): string {
  const lines = ['| Type | What happened |', '|---|---|']
  for (const e of eventTypesOf(document))
    lines.push(`| \`${e.type}\` | ${cell(e.description)} |`)
  return lines.join('\n')
}

/** Replace what lies between `<!-- name -->` and `<!-- /name -->` with `body`. */
function fillBetween(markdown: string, name: string, body: string, page: string): string {
  const open = `<!-- ${name} -->`
  const close = `<!-- /${name} -->`
  const at = markdown.indexOf(open)
  const end = markdown.indexOf(close)
  if (at === -1 || end === -1 || end < at)
    throw new Error(`${page}: needs \`${open}\` … \`${close}\` for its generated table`)
  return `${markdown.slice(0, at + open.length)}\n\n${body}\n\n${markdown.slice(end)}`
}

/** Every `<!-- example: <file> -->` … `<!-- /example -->` span, filled with that file. */
async function fillExamples(markdown: string, page: string): Promise<string> {
  const pattern = /<!-- example: ([a-z0-9-]+) -->[\s\S]*?<!-- \/example -->/g
  let out = ''
  let from = 0
  for (const m of markdown.matchAll(pattern)) {
    const name = m[1]!
    let text: string
    try {
      text = await readFile(join(EXAMPLES_DIR, `${name}.ts`), 'utf8')
    } catch {
      throw new Error(`${page}: names the example ${name}, and ${name}.ts does not exist`)
    }
    out += markdown.slice(from, m.index)
    out += `<!-- example: ${name} -->\n\n\`\`\`ts\n${text.trimEnd()}\n\`\`\`\n\n<!-- /example -->`
    from = m.index + m[0].length
  }
  return out + markdown.slice(from)
}

/** The hand-written pages: every `*.md` under `docs/api` but `reference/`. */
async function handWritten(): Promise<string[]> {
  return (await readdir(DOCS_DIR)).filter((f) => f.endsWith('.md')).sort()
}

const titleOf = (markdown: string): string =>
  (markdown.split('\n').find((l) => l.startsWith('# ')) ?? '# ').slice(2).trim()

/** The first prose paragraph after the title — the same rule the control plane's index uses. */
function summaryOf(markdown: string): string {
  const lines = markdown.split('\n')
  const paragraph: string[] = []
  for (const raw of lines.slice(lines.findIndex((l) => l.startsWith('# ')) + 1)) {
    const line = raw.trim()
    if (paragraph.length > 0 && line === '') break
    const prose = line !== '' && !/^(#|```|\||<!--)/.test(line)
    if (prose) paragraph.push(line)
    else if (paragraph.length > 0) break
  }
  return paragraph.join(' ')
}

function llmsTxt(pages: { file: string; markdown: string }[]): string {
  const slug = (file: string) => file.replace(/\.md$/, '').split('/').join('-')
  const lines = [
    '# Manifest',
    '',
    '> Manifest is UBC’s self-hosted platform for building, deploying and launching applications with CWL sign-in. Its API is the only way in, for a person’s tools and for an AI agent alike: create a project, read and commit its code, set its secrets, build, release, deploy and launch. Every request carries a session or a delegated token (`Authorization: Bearer mft_…`); a privileged action waits for a person.',
    '',
    'Each page below is served by the API as Markdown at `GET /v1/docs/{slug}` (any credential), and the OpenAPI document is `GET /v1/openapi.json`. An agent reads `agents` first.',
    '',
    '## Guides',
    '',
  ]
  // The convention's one line per page: the title, and the first sentence of its summary.
  const firstSentence = (text: string) => text.split(/(?<=[.!?])\s/, 1)[0]!
  const line = (p: { file: string; markdown: string }) =>
    `- [${titleOf(p.markdown)}](/v1/docs/${slug(p.file)}): ${firstSentence(summaryOf(p.markdown))}`
  for (const p of pages.filter((p) => !p.file.startsWith('reference/')))
    lines.push(line(p))
  lines.push('', '## Reference', '')
  for (const p of pages.filter((p) => p.file.startsWith('reference/')))
    lines.push(line(p))
  lines.push(
    '',
    '## The document',
    '',
    '- [OpenAPI 3.1](/v1/openapi.json): every operation, representation, error code and event.',
    '',
  )
  return lines.join('\n')
}

/**
 * EVERY FILE `docs:write` OWNS, as it would write it: `docs/api/…` relative paths (and the
 * console's copy of `llms.txt`, by its absolute path) to their full text.
 */
export async function generateDocs(): Promise<Map<string, string>> {
  const document = JSON.parse(await readFile(DOCUMENT, 'utf8')) as Json
  const out = new Map<string, string>()
  const generatedReference: [string, string][] = [
    ['reference/operations.md', operationsPage(document)],
    ['reference/errors.md', errorsPage(document)],
    ['reference/events.md', eventsReferencePage(document)],
    ['reference/manifest-yaml.md', manifestYamlPage(document)],
  ]
  for (const file of await handWritten()) {
    let markdown = await readFile(join(DOCS_DIR, file), 'utf8')
    markdown = await fillExamples(markdown, file)
    if (file === 'journey.md')
      markdown = fillBetween(markdown, 'journey', journeyTable(), file)
    if (file === 'events.md')
      markdown = fillBetween(markdown, 'event-types', eventTypesTable(document), file)
    out.set(file, markdown)
  }
  for (const [file, markdown] of generatedReference) out.set(file, markdown)
  const llms = llmsTxt(
    [...out.entries()]
      .map(([file, markdown]) => ({ file, markdown }))
      .sort((a, b) =>
        a.file === 'index.md' ? -1 : b.file === 'index.md' ? 1 : a.file < b.file ? -1 : 1,
      ),
  )
  out.set('llms.txt', llms)
  out.set(LLMS_COPY, llms)
  return out
}

/** Where a key of `generateDocs`'s map is written. */
export const pathOf = (key: string): string =>
  key.startsWith('/') ? key : join(DOCS_DIR, key)

async function main(): Promise<void> {
  const files = await generateDocs()
  for (const [key, text] of files) {
    await mkdir(dirname(pathOf(key)), { recursive: true })
    await writeFile(pathOf(key), text)
    console.log(`wrote ${relative(REPO, pathOf(key))}`)
  }
}

if (
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  await main()
}
