import type { LiteLlmClient } from '../ai/index.js'
import type { SpecChange } from '../spec/index.js'

/** Where the summary in a `diff_snapshot` came from, or why there is none (Decision 7). */
export type SummarySource = 'llm' | 'unavailable' | 'no-previous-release'

export interface ChangeSummary {
  summary: string | null
  summarySource: SummarySource
}

/**
 * §10's catalogue name, and the reason D17's routing question does not arise: the input is
 * a `manifest.yaml` diff — configuration, not personal information — and this model carries
 * `max_classification: confidential`, so nothing here needs a claim about where it goes.
 *
 * A LOGICAL name, never a vendor model id. `ai/errors.ts`'s hint for `AI_MODEL_UNKNOWN`
 * says the same thing to an app, and the platform holds itself to it.
 */
export const SUMMARY_MODEL = 'default-chat-onprem'

/**
 * §13's "AI-written plain-English summary of what changed since the last approved release",
 * for the administrator to read at decision time.
 *
 * **A FAILED SUMMARY DOES NOT BLOCK AN APPROVAL** (Decision 7). An approval gate that fails
 * closed on a language model being down is an outage, not a control — and §13's control is
 * the administrator reading the DIFF, which is stored beside this and is not generated by
 * anything. So a failure is recorded as `summary: null` with `summarySource: 'unavailable'`,
 * and the reason goes to the operator.
 *
 * **"ABSENT" IS REACHABLE BECAUSE `ai/client.ts` HAS A 10 s TIMEOUT.** A synchronous call
 * with no timeout would turn a dead gateway into an approval request that never answers,
 * which is the same outage by a longer road.
 */
export async function summariseChanges(
  ai: LiteLlmClient | undefined,
  changes: readonly SpecChange[],
): Promise<ChangeSummary> {
  // MANIFEST_AI_ENABLED=0 is a real configuration (`src/index.ts` builds no client at all),
  // so `ai` can be absent. NOT an error: it is the same "recorded as absent" answer by a
  // different route, and an administrator reads the diff either way.
  if (ai === undefined) return { summary: null, summarySource: 'unavailable' }
  if (changes.length === 0)
    return {
      summary: 'Nothing in manifest.yaml changed since the last approved release.',
      summarySource: 'llm',
    }
  try {
    const answer = await ai.post<{ choices: { message: { content: string } }[] }>(
      '/chat/completions',
      {
        model: SUMMARY_MODEL,
        messages: [
          {
            role: 'system',
            content:
              'You summarise changes to a university web application’s configuration for an administrator ' +
              'deciding whether to allow it into production. Three sentences at most. Plain English. ' +
              'Say what changed and why it might matter. Do not invent anything that is not in the list.',
          },
          {
            role: 'user',
            content: changes
              .map((c) => `${c.path}: ${c.from} -> ${c.to} (${c.summary})`)
              .join('\n'),
          },
        ],
        max_tokens: 200,
      },
    )
    const text = answer.choices[0]?.message.content?.trim()
    // AN EMPTY ANSWER IS AN ABSENT ONE, not an empty summary: a blank line in the record
    // would read as "nothing changed" beside a list of changes.
    return text
      ? { summary: text, summarySource: 'llm' }
      : { summary: null, summarySource: 'unavailable' }
  } catch (error) {
    // NOT SWALLOWED. `.catch(() => undefined)` is this codebase's most productive defect,
    // and a failure with no operator line hides the next one. `AiError`'s message is
    // already mapped and carries no key hash (`ai/client.ts`), and `console.error` rather
    // than `request.log`, which writes nothing under `Fastify({ logger: false })`.
    console.error(
      `[approval] the change summary could not be produced: ${(error as Error).message}`,
    )
    return { summary: null, summarySource: 'unavailable' }
  }
}
