import type { LiteLlmClient } from '../ai/index.js'
import type { SensitiveField, SpecChange } from '../spec/index.js'

/**
 * Where the summary in a `diff_snapshot` came from, or why there is none (Decision 7).
 * `no-changes` (P6b Task 8): the fixed sentence for an empty diff, which no model wrote —
 * P6a recorded it as `llm`, and its acceptance printed it as "the model's summary".
 */
export type SummarySource = 'llm' | 'unavailable' | 'no-previous-release' | 'no-changes'

/**
 * R4(d)'s context (P6b Task 8, Decision 13): what the model is told BESIDE the changes — the
 * deterministic security notes, the reviewer's verdict at decision time, and D33's coverage
 * limit. The notes and the verdict are the record's own; the model only phrases them.
 */
export interface SummaryContext {
  security: readonly { field: SensitiveField; note: string }[]
  review: { state: string; reviewer: string; detail: string }
  coverage: string
}

/** The one sentence an empty diff has, whoever writes it — never a model. */
const NO_CHANGES = 'Nothing in manifest.yaml changed since the last approved release.'

/**
 * R4(d)'s system prompt. **Security-aware and verdict-carrying, and plain text**: `[M12]`
 * measured the model writing `**host**` under "plain English", and the console renders the
 * stored summary as text. The record is what the administrator was shown, verbatim, so the
 * prompt asks for plain text and nothing strips it afterwards — a model that still writes
 * Markdown is a finding for the clicked acceptance, not something to repair here.
 */
const SYSTEM_PROMPT =
  'You summarise changes to a university web application’s configuration for a platform administrator ' +
  'deciding whether to allow it into production. Three sentences at most, plain English. Say what changed ' +
  'and what each change could expose — personal information, where data can go, what the app can reach. ' +
  'State the code reviewer’s verdict exactly as given, in one sentence. Never say or imply that the ' +
  'application’s code was reviewed unless the verdict says it was. Do not invent anything that is not in ' +
  'the list. Write plain text: no Markdown, no asterisks, no bullet characters.'

export interface ChangeSummary {
  summary: string | null
  summarySource: SummarySource
}

/**
 * §10's catalogue name, and the reason D17's routing question does not arise: the input is
 * a `manifest.yaml` diff — configuration, not personal information — and this model carries
 * `max_classification: confidential`, so nothing here needs a claim about where it goes.
 *
 * A LOGICAL name, never a vendor model id. `ai/errors.ts`'s hint for `AI_MODEL_UNKNOWN`
 * says the same thing to an app, and the platform holds itself to it.
 */
export const SUMMARY_MODEL = 'default-chat-onprem'

/**
 * §13's "AI-written plain-English summary of what changed since the last approved release",
 * for the administrator to read at decision time.
 *
 * **A FAILED SUMMARY DOES NOT BLOCK AN APPROVAL** (Decision 7). An approval gate that fails
 * closed on a language model being down is an outage, not a control — and §13's control is
 * the administrator reading the DIFF, which is stored beside this and is not generated by
 * anything. So a failure is recorded as `summary: null` with `summarySource: 'unavailable'`,
 * and the reason goes to the operator.
 *
 * **"ABSENT" IS REACHABLE BECAUSE `ai/client.ts` HAS A 10 s TIMEOUT.** A synchronous call
 * with no timeout would turn a dead gateway into an approval request that never answers,
 * which is the same outage by a longer road.
 */
export async function summariseChanges(
  ai: LiteLlmClient | undefined,
  changes: readonly SpecChange[],
  context: SummaryContext,
): Promise<ChangeSummary> {
  // AN EMPTY DIFF HAS ONE RIGHT ANSWER, and it needs no model — so it is given whether or not
  // one is configured, and recorded as what it is (`no-changes`), never as the model's.
  if (changes.length === 0) return { summary: NO_CHANGES, summarySource: 'no-changes' }
  // MANIFEST_AI_ENABLED=0 is a real configuration (`src/index.ts` builds no client at all),
  // so `ai` can be absent. NOT an error: it is the same "recorded as absent" answer by a
  // different route, and an administrator reads the diff — and the security notes — either way.
  if (ai === undefined) return { summary: null, summarySource: 'unavailable' }
  try {
    const answer = await ai.post<{ choices: { message: { content: string } }[] }>(
      '/chat/completions',
      {
        model: SUMMARY_MODEL,
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          {
            role: 'user',
            // The changes, then the notes (only when a sensitive field changed), then the
            // verdict, then the coverage sentence — each under its own label, so the model
            // can state the verdict "exactly as given".
            content: [
              ...changes.map((c) => `${c.path}: ${c.from} -> ${c.to} (${c.summary})`),
              ...(context.security.length === 0
                ? []
                : [
                    '',
                    'Security notes:',
                    ...context.security.map((s) => `${s.field}: ${s.note}`),
                  ]),
              '',
              `Code review: ${context.review.detail}`,
              '',
              context.coverage,
            ].join('\n'),
          },
        ],
        max_tokens: 200,
      },
    )
    const text = answer.choices[0]?.message.content?.trim()
    // AN EMPTY ANSWER IS AN ABSENT ONE, not an empty summary: a blank line in the record
    // would read as "nothing changed" beside a list of changes.
    return text
      ? { summary: text, summarySource: 'llm' }
      : { summary: null, summarySource: 'unavailable' }
  } catch (error) {
    // NOT SWALLOWED. `.catch(() => undefined)` is this codebase's most productive defect,
    // and a failure with no operator line hides the next one. `AiError`'s message is
    // already mapped and carries no key hash (`ai/client.ts`), and `console.error` rather
    // than `request.log`, which writes nothing under `Fastify({ logger: false })`.
    console.error(
      `[approval] the change summary could not be produced: ${(error as Error).message}`,
    )
    return { summary: null, summarySource: 'unavailable' }
  }
}
