import type { EngineClient } from './engine.js'
import { appNetwork, egressContainer, type EnvironmentKind } from './names.js'

/**
 * §12's platform baseline: the package mirror, the AI proxy and the IdP. NOT the
 * public registries — Verdaccio is the only dependency source, which is what makes
 * C1's offline claim true and gives the supply-chain controls something to enforce.
 */
export const PLATFORM_EGRESS_BASELINE: readonly string[] = [
  '^manifest-verdaccio$',
  '^manifest-litellm$',
  '^manifest-idp$',
]
// NOT `manifest-registry`. §12's baseline is "the registry MIRROR, LiteLLM, the
// Manifest IdP" — the package mirror, not the image registry. A running app has no
// reason to reach the image registry, and §13 spends a section on making sure it
// cannot push to one. P1's own `manifest-egress` allowlist is the platform's and is
// a different file.

const HOSTNAME = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$/i

export class EgressError extends Error {
  readonly code = 'EGRESS_ALLOW_INVALID'
  constructor(
    readonly entry: string,
    readonly hint: string,
  ) {
    super(`EGRESS_ALLOW_INVALID: '${entry}' is not a plain hostname`)
    this.name = 'EgressError'
  }
}

/**
 * Anchored and escaped, always. tinyproxy matches each line as an extended regular
 * expression against the host, so an unanchored `api.ubc.ca` also matches
 * `api.ubc.ca.evil.example` — the allowlist would then be decorative.
 */
export function renderAllowlist(declared: readonly string[]): string {
  const entries = declared.map((host) => {
    if (!HOSTNAME.test(host)) {
      throw new EgressError(
        host,
        'egress.allow takes bare hostnames — no scheme, no path, no wildcard. ' +
          'Wildcards are refused rather than translated, because the translation is where the hole gets in.',
      )
    }
    return `^${host.replace(/\./g, '\\.')}$`
  })
  return [
    '# Generated by the Manifest Docker driver. Do not edit.',
    "# Platform baseline (§12) followed by this app's declared egress.allow.",
    ...PLATFORM_EGRESS_BASELINE,
    ...entries,
    '',
  ].join('\n')
}

/** The forced proxy, in the four spellings every HTTP client actually reads. */
export function proxyEnvironment(url: string): Record<string, string> {
  return {
    HTTP_PROXY: url,
    HTTPS_PROXY: url,
    http_proxy: url,
    https_proxy: url,
    NO_PROXY: 'localhost,127.0.0.1',
  }
}

export async function ensureEgressProxy(
  engine: EngineClient,
  input: { slug: string; kind: EnvironmentKind; allow: readonly string[] },
): Promise<{ name: string; url: string }> {
  const name = egressContainer(input.slug, input.kind)
  const url = `http://${name}:8888`
  const existing = await engine.get<{ State: { Running: boolean } }>(
    `/containers/${name}/json`,
  )
  if (existing) {
    if (!existing.State.Running) await engine.post(`/containers/${name}/start`)
    return { name, url }
  }

  // The allowlist is passed as the container's command rather than a bind mount:
  // the control plane is a host process and the daemon is in a VM, so a host path
  // is not necessarily visible to it. Writing the file from inside the container
  // keeps the driver free of any assumption about shared filesystems.
  const allowlist = renderAllowlist(input.allow)
  const config = [
    'Port 8888',
    'Listen 0.0.0.0',
    'Timeout 600',
    'LogLevel Warning',
    'MaxClients 32',
    // NOT tinyproxy's own `User`/`Group`. P1's platform proxy uses them, but it
    // runs with CapDrop=[]; this one drops ALL capabilities, so tinyproxy cannot
    // setuid and dies with `Unable to change to group "nobody"` (measured). The
    // container is started as 65534:65534 instead — already unprivileged, so no
    // capability is needed to get there. Strictly stronger than dropping to it.
    // P1 measured this as LOAD-BEARING on tinyproxy 1.11.0: a denied request is
    // exactly when tinyproxy renders an error page, and without DefaultErrorFile
    // the process exited (cleanly, code 0) after serving the 403 — with
    // `RestartPolicy: unless-stopped` hiding it, so the proxy was briefly down
    // after every denial and an allowed request racing it got "Empty reply from
    // server". It does NOT reproduce on the 1.11.2 this image ships today
    // (measured 2026-09-06: 3 denials, 0 restarts, in three config variants).
    // Kept anyway: it costs one line and the failure it prevents is racy.
    'DefaultErrorFile "/usr/share/tinyproxy/default.html"',
    'StatFile "/usr/share/tinyproxy/stats.html"',
    'FilterDefaultDeny Yes',
    'Filter "/tmp/allowlist"',
    'FilterURLs Off',
    // tinyproxy 1.11.2 warns that FilterExtended is deprecated "use FilterType".
    // DO NOT take that advice: measured, `FilterType extended` is not understood
    // by 1.11.2 and the proxy fails to start, so EVERY request returns 000 —
    // allowed and denied alike. A deny-only check still sees a refusal and passes,
    // which is why the "ALLOWS the platform baseline" test is the control here.
    'FilterExtended On',
  ].join('\n')

  await engine.post(`/containers/create?name=${name}`, {
    // manifest-egress:local, NOT vimagick/tinyproxy. P1 replaced that image
    // because it is amd64-only and ran under emulation on arm64; the local build
    // is native and, unlike vimagick, is present offline. Its tinyproxy.conf must
    // also set DefaultErrorFile, or the proxy EXITS after serving each denial.
    Image: 'manifest-egress:local',
    // nobody:nogroup. See the note beside the config above: this is how the proxy
    // becomes non-root, because CapDrop:["ALL"] forbids tinyproxy doing it itself.
    User: '65534:65534',
    Entrypoint: ['/bin/sh', '-c'],
    Cmd: [
      `printf '%s\\n' "$ALLOWLIST" > /tmp/allowlist && ` +
        `printf '%s\\n' "$TINYPROXY_CONF" > /tmp/tinyproxy.conf && ` +
        `exec tinyproxy -d -c /tmp/tinyproxy.conf`,
    ],
    Env: [`ALLOWLIST=${allowlist}`, `TINYPROXY_CONF=${config}`],
    HostConfig: {
      NetworkMode: appNetwork(input.slug, input.kind),
      CapDrop: ['ALL'],
      SecurityOpt: ['no-new-privileges'],
      Privileged: false,
      PidsLimit: 64,
      Memory: 64 * 1024 * 1024,
      RestartPolicy: { Name: 'unless-stopped' },
    },
    Labels: { 'manifest.slug': input.slug, 'manifest.environment': input.kind },
  })
  // DUAL-HOMED, and this is the one container that is. The app network is internal;
  // the proxy is the only thing on it with a way out (S1's registry pattern).
  await engine.post('/networks/manifest-platform/connect', { Container: name })
  await engine.post(`/containers/${name}/start`)
  return { name, url }
}

export async function destroyEgressProxy(
  engine: EngineClient,
  slug: string,
  kind: EnvironmentKind,
): Promise<void> {
  await engine.del(`/containers/${egressContainer(slug, kind)}?force=true&v=true`)
}
