import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * A throwaway self-signed issuer for tests.
 *
 * GENERATED, never committed. The obvious alternative — commit the pair under
 * `__fixtures__/` — cannot work here: this repo's `.gitignore` carries a blanket
 * `*.key` under "Environment and secrets — never commit these", so `git add`
 * SILENTLY skips the private half. The result passes on the machine that made it
 * and fails on every clone with `ENOENT`, which is precisely the second-machine
 * gap P1 already has open. Negating the rule for one path would weaken the one
 * guard that stops a real key being committed by accident.
 *
 * So it is generated on first use into a gitignored directory and reused after
 * that: no key in the repository, no per-run cost, nothing for Task 11's secret
 * scanner to have to make an exception for, and one directory rather than a temp
 * directory per process.
 *
 * It signs nothing outside this suite; the real issuer is generated by `make seed`
 * into the gitignored `infra/registry-auth/`.
 */
// src/runtime/docker/ -> packages/control-plane/
const FIXTURES = fileURLToPath(new URL('../../../.test-fixtures/', import.meta.url))

export function testIssuer(): {
  keyPem: string
  certPem: string
  keyPath: string
  certPath: string
} {
  const keyPath = join(FIXTURES, 'token.key')
  const certPath = join(FIXTURES, 'token.crt')
  if (!existsSync(keyPath) || !existsSync(certPath)) {
    mkdirSync(FIXTURES, { recursive: true })
    execFileSync('openssl', [
      'req',
      '-x509',
      '-newkey',
      'rsa:2048',
      '-nodes',
      '-days',
      '3650',
      '-keyout',
      keyPath,
      '-out',
      certPath,
      '-subj',
      '/CN=manifest-test-issuer',
    ])
  }
  return {
    keyPem: readFileSync(keyPath, 'utf8'),
    certPem: readFileSync(certPath, 'utf8'),
    keyPath,
    certPath,
  }
}

/**
 * The repository root, derived from this file rather than from `process.cwd()`.
 *
 * `pnpm test` and `pnpm --filter … test` set DIFFERENT working directories, and a
 * cwd-relative path in a test passes under one and `ENOENT`s under the other —
 * measured twice in P2. Anything reaching for `infra/` from a test goes through
 * this.
 */
// src/runtime/docker/ -> the repository root
export const REPO_ROOT = fileURLToPath(new URL('../../../../../', import.meta.url))
