import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import type { Driver } from '../driver.js'
import { createCaddyClient } from '../../routing/index.js'
import { createDockerDriver } from './driver.js'
import { createEngineClient, resolveSocketPath } from './engine.js'
import { fileURLToPath } from 'node:url'

/**
 * A throwaway self-signed issuer for tests.
 *
 * GENERATED, never committed. The obvious alternative — commit the pair under
 * `__fixtures__/` — cannot work here: this repo's `.gitignore` carries a blanket
 * `*.key` under "Environment and secrets — never commit these", so `git add`
 * SILENTLY skips the private half. The result passes on the machine that made it
 * and fails on every clone with `ENOENT`, which is precisely the second-machine
 * gap P1 already has open. Negating the rule for one path would weaken the one
 * guard that stops a real key being committed by accident.
 *
 * So it is generated on first use into a gitignored directory and reused after
 * that: no key in the repository, no per-run cost, nothing for Task 11's secret
 * scanner to have to make an exception for, and one directory rather than a temp
 * directory per process.
 *
 * It signs nothing outside this suite; the real issuer is generated by `make seed`
 * into the gitignored `infra/registry-auth/`.
 */
// src/runtime/docker/ -> packages/control-plane/
const FIXTURES = fileURLToPath(new URL('../../../.test-fixtures/', import.meta.url))

export function testIssuer(): {
  keyPem: string
  certPem: string
  keyPath: string
  certPath: string
} {
  const keyPath = join(FIXTURES, 'token.key')
  const certPath = join(FIXTURES, 'token.crt')
  if (!existsSync(keyPath) || !existsSync(certPath)) {
    mkdirSync(FIXTURES, { recursive: true })
    execFileSync('openssl', [
      'req',
      '-x509',
      '-newkey',
      'rsa:2048',
      '-nodes',
      '-days',
      '3650',
      '-keyout',
      keyPath,
      '-out',
      certPath,
      '-subj',
      '/CN=manifest-test-issuer',
    ])
  }
  return {
    keyPem: readFileSync(keyPath, 'utf8'),
    certPem: readFileSync(certPath, 'utf8'),
    keyPath,
    certPath,
  }
}

/**
 * The repository root, derived from this file rather than from `process.cwd()`.
 *
 * `pnpm test` and `pnpm --filter … test` set DIFFERENT working directories, and a
 * cwd-relative path in a test passes under one and `ENOENT`s under the other —
 * measured twice in P2. Anything reaching for `infra/` from a test goes through
 * this.
 */
// src/runtime/docker/ -> the repository root
export const REPO_ROOT = fileURLToPath(new URL('../../../../../', import.meta.url))

/** The platform CA `make seed` mints. Absolute, and root-relative for the reason
 *  REPO_ROOT exists — `docker run -v` on a relative path that does not resolve
 *  creates a DIRECTORY at that name instead of failing (verify.sh guards the same
 *  way, and defect 27 paid for it once). */
export const CA_CERT = join(REPO_ROOT, 'infra/ca/manifest-root.crt')

/**
 * A Driver backed by the real daemon, for `driver-contract.ts`.
 *
 * The contract suite hardcodes its own inputs — `repoPath: '/tmp/repo'`,
 * `commitSha: 'abc123'` — because it was written against an in-memory fake. Both
 * are satisfiable against real Docker without touching the suite:
 *
 *  * `/tmp/repo` is created here as a real BARE repository holding the fixture
 *    blueprint's skeleton, and
 *  * `abc123` is created as a real TAG on its one commit. `assembleContext` runs
 *    `git archive <commitSha>`, which takes any tree-ish, so a tag by that name
 *    resolves exactly as a sha would.
 *
 * The issuer is the REAL one from `infra/registry-auth/`, not `testIssuer()`:
 * registry:2 validates against `token.crt`, so a self-signed test pair mints
 * tokens the running registry refuses.
 */
export function dockerDriverForTests(
  overrides: { readinessTimeoutMs?: number } = {},
): Promise<Driver> {
  const keyPath = join(REPO_ROOT, 'infra/registry-auth/token.key')
  const certPath = join(REPO_ROOT, 'infra/registry-auth/token.crt')
  if (!existsSync(keyPath) || !existsSync(certPath)) {
    throw new Error(
      `no registry issuer at ${keyPath}. Run \`make up\`, which calls ` +
        'infra/lib/ensure-registry-auth.sh.',
    )
  }
  return createDockerDriver({
    engine: createEngineClient({ socketPath: resolveSocketPath() }),
    // A fixed, non-secret value: these are throwaway containers on a laptop, and a
    // random one per run would orphan the previous run's service volumes.
    masterSecret: 'contract-suite-master-secret',
    // Resolves the REFERENCE, exactly as the control plane does, so this suite
    // exercises the same seam rather than a fixed directory the boot path never
    // uses. `fixture-node@1` is the only blueprint P3 has.
    blueprintDirFor: (ref: string) => {
      const dir = join(REPO_ROOT, 'blueprints', ref.split('@')[0]!)
      if (!existsSync(join(dir, 'blueprint.yaml'))) {
        throw new Error(`no blueprint '${ref}' — looked in ${dir}`)
      }
      return dir
    },
    dnsServer: '10.89.0.53',
    registryHost: 'manifest-registry:5000',
    registryPublicHost: '127.0.0.1:7107',
    registryTokenKeyPem: readFileSync(keyPath, 'utf8'),
    registryTokenCertPem: readFileSync(certPath, 'utf8'),
    hostnameFor: (kind, slug) =>
      kind === 'production'
        ? `${slug}.manifest.internal`
        : `${slug}.${kind}.manifest.internal`,
    routing: {
      caddy: createCaddyClient('http://127.0.0.1:7119'),
      servers: { internal: 'srv0', public: 'srv0' },
    },
    caCertPath: CA_CERT,
    // 90 s by default, which a test that WANTS the timeout cannot afford to wait.
    ...(overrides.readinessTimeoutMs === undefined
      ? {}
      : { readinessTimeoutMs: overrides.readinessTimeoutMs }),
  })
}

/**
 * The bare repository the contract suite names. Idempotent, and it deliberately
 * uses a TAG for the commit-ish so `git archive 'abc123'` resolves.
 */
export function ensureContractRepo(repoPath = '/tmp/repo'): void {
  if (existsSync(join(repoPath, 'HEAD'))) return
  const work = mkdtempSync(join(tmpdir(), 'mf-contract-src-'))
  try {
    const skeleton = join(REPO_ROOT, 'blueprints/fixture-node/skeleton')
    execFileSync('sh', [
      '-c',
      `cp -R ${JSON.stringify(skeleton)}/. ${JSON.stringify(work)}/`,
    ])
    // §12's mandatory gates run before every build and BLOCK: the lockfile gate
    // refuses a context without one. The skeleton is a template, not an installed
    // tree, so the fixture supplies the lockfile the gate requires.
    if (!existsSync(join(work, 'package-lock.json'))) {
      writeFileSync(
        join(work, 'package-lock.json'),
        JSON.stringify(
          { name: 'contract-fixture', lockfileVersion: 3, packages: {} },
          null,
          2,
        ),
      )
    }
    const git = (...args: string[]): void => {
      execFileSync('git', args, {
        cwd: work,
        env: {
          ...process.env,
          GIT_AUTHOR_NAME: 'manifest',
          GIT_AUTHOR_EMAIL: 'manifest@localhost',
          GIT_COMMITTER_NAME: 'manifest',
          GIT_COMMITTER_EMAIL: 'manifest@localhost',
        },
      })
    }
    git('init', '-q', '-b', 'main')
    git('add', '-A')
    git('commit', '-q', '-m', 'contract fixture')
    // The suite's literal commit-ish. A tag, because a sha cannot be chosen.
    git('tag', 'abc123')
    execFileSync('git', ['clone', '--bare', '-q', work, repoPath])
  } finally {
    rmSync(work, { recursive: true, force: true })
  }
}

/**
 * `fixtures/fixture-app` as a real bare repository at a real commit.
 *
 * Distinct from `ensureContractRepo`, which serves the contract suite's hardcoded
 * `/tmp/repo` + `abc123` literals with the blueprint SKELETON. This one carries the
 * fixture APP — a different tree, a real sha — because Task 17's claim is that an
 * app the platform did not write builds and runs, and the skeleton is the
 * blueprint's own file.
 *
 * Idempotent across runs: the bare repo is rebuilt whenever the source tree is
 * newer, so editing the fixture app does not silently test the previous commit.
 */
export function fixtureBareRepo(
  repoPath = join(tmpdir(), 'mf-fixture-app.git'),
  options: { source?: string; extraFiles?: Record<string, string> } = {},
): {
  repoPath: string
  commitSha: string
} {
  const source = options.source ?? join(REPO_ROOT, 'fixtures/fixture-app')
  // `extraFiles` are files the platform would MOUNT rather than commit — the
  // IdP's public signing certificate, for the SAML fixture. They are part of the
  // stamp because a certificate that changes must produce a new image; leaving
  // them out would reuse a stale one and the login would fail signature
  // validation against a certificate nobody had changed.
  const extra = options.extraFiles ?? {}
  const extraStamp = Object.entries(extra)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, contents]) => `${name}:${contents}`)
    .join('\n')
  const sourceStamp = execFileSync('sh', [
    '-c',
    `cat ${JSON.stringify(source)}/* | shasum -a 256 | cut -c1-16`,
  ])
    .toString()
    .trim()
  const stamp =
    extraStamp === ''
      ? sourceStamp
      : `${sourceStamp}-${createHash('sha256').update(extraStamp).digest('hex').slice(0, 16)}`
  const stampFile = join(repoPath, 'manifest-fixture-stamp')
  const current = existsSync(stampFile) ? readFileSync(stampFile, 'utf8').trim() : ''
  if (current !== stamp) {
    rmSync(repoPath, { recursive: true, force: true })
    const work = mkdtempSync(join(tmpdir(), 'mf-fixture-src-'))
    try {
      execFileSync('sh', [
        '-c',
        `cp -R ${JSON.stringify(source)}/. ${JSON.stringify(work)}/`,
      ])
      for (const [name, contents] of Object.entries(extra)) {
        writeFileSync(join(work, name), contents)
      }
      const git = (...args: string[]): void => {
        execFileSync('git', args, {
          cwd: work,
          env: {
            ...process.env,
            GIT_AUTHOR_NAME: 'manifest',
            GIT_AUTHOR_EMAIL: 'manifest@localhost',
            GIT_COMMITTER_NAME: 'manifest',
            GIT_COMMITTER_EMAIL: 'manifest@localhost',
            // Fixed, so the same tree gives the same sha and — through
            // SOURCE_DATE_EPOCH, which is the COMMIT's time — the same digest.
            GIT_AUTHOR_DATE: '2026-01-01T00:00:00Z',
            GIT_COMMITTER_DATE: '2026-01-01T00:00:00Z',
          },
        })
      }
      git('init', '-q', '-b', 'main')
      git('add', '-A')
      git('commit', '-q', '-m', 'fixture app')
      execFileSync('git', ['clone', '--bare', '-q', work, repoPath])
      writeFileSync(stampFile, `${stamp}\n`)
    } finally {
      rmSync(work, { recursive: true, force: true })
    }
  }
  const commitSha = execFileSync('git', [`--git-dir=${repoPath}`, 'rev-parse', 'HEAD'])
    .toString()
    .trim()
  return { repoPath, commitSha }
}
