/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/blueprints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The blueprint catalogue
         * @description §22 step 2: what a person chooses from, with the starters each offers (§25).
         */
        get: operations["listBlueprints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/blueprints/{blueprintRef}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A blueprint
         * @description One blueprint by `name@major`.
         */
        get: operations["getBlueprint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/blueprints/{blueprintRef}/knowledge-pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A blueprint’s knowledge pack
         * @description D25: served over the API and versioned with its blueprint, so an agent learns the conventions without running inside the platform. Each file carries its sha256.
         */
        get: operations["getKnowledgePack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/builds/{buildId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A build
         * @description Its present status, image digest, the reason a failed build failed, and its scan (§12).
         */
        get: operations["getBuild"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/builds/{buildId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A build’s log
         * @description §14: every line, redacted at capture — or the last `tail`. Lines arrive live on the project’s event stream while the build runs; this is every one of them afterwards.
         */
        get: operations["getBuildLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/environments/{environmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * An environment, and what it serves
         * @description The environment and the instance its hostname reaches (§6 Route) — not the newest deploy, which may have failed.
         */
        get: operations["getEnvironment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in person
         * @description Who this session belongs to, and the platform role it is authorized as. Every client calls it first.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The projects I am a member of
         * @description Every project the caller owns or collaborates on, newest first — for administrators too. The fleet is GET /v1/fleet.
         */
        get: operations["listProjects"];
        put?: never;
        /**
         * Create a project
         * @description §22 steps 2–3: a name, a blueprint, optionally a starter, and who the app is for (§24). Creates the project and its three environments, seeds a repository from the skeleton and the starter, and validates its manifest. Progress is on the project’s event stream: project.created, repository.seeded, spec.validated.
         */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A project
         * @description One project; `?expand=environments` includes its three environments, each with the instance it serves (D23.1).
         */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/builds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A project’s builds
         * @description The newest 50, newest first.
         */
        get: operations["listBuilds"];
        put?: never;
        /**
         * Build the project
         * @description §22 step 4. Answers 202 at once with the build `running` (R6); its log lines arrive as `log` frames and its end as `build.succeeded` or `build.failed` on the project’s event stream. GET /v1/builds/{buildId} for the present state — a replayed Idempotency-Key answers the 202 as it was first sent.
         */
        post: operations["startBuild"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A project’s environments
         * @description Sandbox, staging and production — all three exist from the moment the project does (§23).
         */
        get: operations["listEnvironments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The project’s event stream (WebSocket)
         * @description Upgrade to a WebSocket. Builds, their log lines, instance state transitions, incidents and every other audit event for this project, as StreamFrames: the newest events first as a replay, then the ready frame, then live. A session-bearing upgrade must carry Origin (§20). A plain GET answers 426.
         */
        get: operations["streamProjectEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who is a member of a project
         * @description Owners and collaborators (§13). Reading is `project:read`; changing membership is `members:manage`.
         */
        get: operations["listMembers"];
        put?: never;
        /**
         * Add or change a member
         * @description Grants a person who has signed in once a role on the project. One of D24’s privileged four: a delegated token will never hold it (P5b).
         */
        post: operations["addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projects/{projectId}/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The project’s newest valid manifest
         * @description manifest.yaml as last validated (§7). An invalid newest manifest answers SPEC_INVALID with its errors.
         */
        get: operations["getSpec"];
        put?: never;
        /**
         * Validate manifest.yaml at a commit
         * @description §22 step 3: reads manifest.yaml at the commit (HEAD by default), validates it (§7) and records the result. A sensitive diff (D9) is reported, not yet enforced.
         */
        post: operations["validateSpec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/slugs/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Would this project name work?
         * @description §23: answers exactly what project creation will, so a client can tell a person while they type. Always 200 — the answer is about the name, and a 4xx would make "taken" indistinguishable from "not allowed to ask". Says nothing about a holder. 60 a minute per person.
         */
        get: operations["checkSlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddMemberRequest: {
            /** @description The person’s ubcEduCwlPuid. They must have signed in once. */
            puid: string;
            /** @enum {string} */
            role: "owner" | "collaborator";
        };
        Audience: {
            /** @enum {string} */
            scale: "solo" | "class" | "large_course" | "public";
            /** @enum {string} */
            burst: "steady" | "synchronised";
            justification: string | null;
            /** Format: uuid */
            setBy: string;
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            setAt: string;
        };
        AudienceInput: {
            /**
             * @description §24: how many people.
             * @enum {string}
             */
            scale: "solo" | "class" | "large_course" | "public";
            /**
             * @description §24: do they all arrive at once.
             * @enum {string}
             */
            burst: "steady" | "synchronised";
            justification?: string;
        };
        /** @description A blueprint as a client chooses one: what it provides and the starters it offers. Never its base image or build internals. */
        Blueprint: {
            /** @description `name@major` — what a project pins (§25). */
            ref: string;
            name: string;
            majorVersion: number;
            language: string;
            defaultPort: number;
            healthPath: string;
            schemaVersions: number[];
            provides: {
                services: string[];
                authProviders: ("cwl" | "none")[];
                ai: boolean;
            };
            /** @description §25: what `POST /v1/projects` accepts as `starter` for this blueprint. */
            starters: {
                name: string;
                summary: string;
            }[];
        };
        BlueprintList: components["schemas"]["Blueprint"][];
        /** @description A build of one commit (§13). It answers `running` when it starts, and ends as `succeeded` or `failed` on the project’s stream (R6). */
        Build: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            commitSha: string;
            /** @enum {string} */
            status: "pending" | "running" | "succeeded" | "failed";
            /** @description `sha256:…` once the build has succeeded; the image a release names. */
            imageDigest: string | null;
            /** @description Why a failed build failed, in words its author can act on (§14). */
            error: string | null;
            /** @description Null until the build succeeds, and for a build from before scans were recorded. */
            scan: components["schemas"]["ScanSummary"] | null;
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
        };
        BuildList: components["schemas"]["Build"][];
        /** @description §14’s build log, as stored. */
        BuildLog: {
            /** Format: uuid */
            buildId: string;
            lines: {
                seq: number;
                /** @enum {string} */
                stream: "stdout" | "stderr";
                /** @description Redacted at capture (§14). */
                text: string;
                /**
                 * Format: date-time
                 * @description An instant, ISO 8601 in UTC.
                 */
                at: string;
            }[];
        };
        /** @description Ends the replay: everything after it is live. */
        ControlFrame: {
            /** @constant */
            kind: "control";
            id: string;
            /** Format: uuid */
            projectId: string;
            /** @constant */
            type: "manifest.stream.ready";
        };
        CreateProjectRequest: {
            /** @description Checked by the same function as GET /v1/slugs/{slug} (§23). */
            slug: string;
            /** @description `name@major`, from GET /v1/blueprints. */
            blueprint: string;
            /** @description One the blueprint offers. Without one: the skeleton and a minimal manifest. */
            starter?: string;
            audience: components["schemas"]["AudienceInput"];
        };
        /** @description §22 steps 2–3: the project, its environments, and the validation of the manifest its first commit carries. */
        CreatedProject: {
            /** Format: uuid */
            id: string;
            /** @description The project’s name, and the first label of every hostname it has (§23). */
            slug: string;
            /** @description `name@major` (§25). */
            blueprint: string;
            /** @description The starter the first commit was seeded from (§25); null for the skeleton alone. */
            starter: string | null;
            owner: components["schemas"]["UserSummary"];
            audience: components["schemas"]["Audience"] | null;
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
            environments: components["schemas"]["Environment"][];
            spec: components["schemas"]["SpecValidation"];
        };
        EmptyRequest: Record<string, never>;
        Environment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** @enum {string} */
            kind: "sandbox" | "staging" | "production";
            /** @description §23: `<slug>.<zone for this kind>`. Permanent. */
            hostname: string;
            /** Format: uri */
            url: string;
            /** @description The instance the hostname reaches (§6 Route); for an app deployed before P4c, its newest instance. Null before any deploy. */
            instance: components["schemas"]["Instance"] | null;
        };
        EnvironmentList: components["schemas"]["Environment"][];
        /**
         * @description Every code the API answers with (api/error-codes.ts). Stable: a client switches on it (§20).
         * @enum {string}
         */
        ErrorCode: "AI_BACKEND_UNAVAILABLE" | "AI_CATALOGUE_DISABLED" | "AI_CATALOGUE_EMPTY" | "AI_KEY_EXPIRED" | "AI_KEY_REVOKED" | "AI_MODEL_NOT_PERMITTED" | "AI_MODEL_UNKNOWN" | "AI_PROJECT_BUDGET_EXCEEDED" | "AI_ROUTE_NOT_PERMITTED" | "AI_UNMAPPED" | "AI_USER_BUDGET_EXCEEDED" | "BLUEPRINT_NOT_FOUND" | "CONFIG_BUILD_CREDENTIAL_SECRET_REQUIRED" | "CONFIG_CONTROL_PLANE_ORIGIN_PORT_MISMATCH" | "CONFIG_INVALID" | "CONFIG_LITELLM_MASTER_KEY_REQUIRED" | "CONFIG_MASTER_SECRET_REQUIRED" | "CSRF_ORIGIN_REFUSED" | "DEPLOY_INVALID_INPUT" | "EVENTS_UPGRADE_REQUIRED" | "FORBIDDEN" | "IDEMPOTENCY_KEY_REQUIRED" | "IDEMPOTENCY_KEY_REUSED" | "INTERNAL" | "MEMBER_USER_NOT_FOUND" | "NOT_FOUND" | "RATE_LIMITED" | "RELEASE_AI_BUDGET_MISSING" | "RELEASE_AI_DISABLED" | "RELEASE_BLUEPRINT_NOT_FOUND" | "RELEASE_BUILD_NOT_DEPLOYABLE" | "RELEASE_BUILD_NOT_FOUND" | "RELEASE_DIGEST_MISSING" | "RELEASE_ENVIRONMENT_NOT_FOUND" | "RELEASE_IMAGE_REPOSITORY_MISSING" | "RELEASE_INVALID_INPUT" | "RELEASE_LOCAL_IMAGE_ON_REMOTE_DRIVER" | "RELEASE_MODEL_CLASSIFICATION_TOO_LOW" | "RELEASE_MODEL_NOT_IN_CATALOGUE" | "RELEASE_MODEL_UNCLASSIFIED" | "RELEASE_NOT_FOUND" | "RELEASE_PRODUCTION_GATE_UNAVAILABLE" | "RELEASE_PROJECT_NOT_FOUND" | "REQUEST_BODY_TOO_LARGE" | "REQUEST_INVALID" | "REQUEST_MEDIA_TYPE_UNSUPPORTED" | "ROUTE_NOT_FOUND" | "SAML_ASSERTION_REJECTED" | "SAML_LOGIN_NOT_BOUND" | "SAML_NO_PUID" | "SAML_USER_UPSERT_FAILED" | "SLUG_INVALID" | "SLUG_RESERVED" | "SLUG_TAKEN" | "SOURCE_FOREIGN_REPO" | "SOURCE_GIT_FAILED" | "SOURCE_INVALID_SLUG" | "SOURCE_PATH_ESCAPE" | "SPEC_INVALID" | "SPEC_NOT_FOUND" | "STARTER_NOT_FOUND" | "UNAUTHENTICATED";
        ErrorEnvelope: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /** @description For a person. Never parse it; switch on `code`. */
                message: string;
                /** @description What to do about it. */
                hint?: string;
                details?: components["schemas"]["ManifestError"][];
            };
        };
        /** @description An audit Event, as recorded (§20) and redacted at capture (§14). Switch on `type`; each type has one `machineDetail` shape. Replayed on reconnect. */
        EventFrame: {
            /** @constant */
            kind: "event";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** @description What the event is about — `build:<id>`, `instance:<id>`. Opaque. */
            subject: string;
            /** @constant */
            type: "sso.registered";
            /** @description For a person (§14). Never parse it. */
            humanMessage: string;
            machineDetail: {
                entityId: string;
                acsUrl: string;
                attributes: string[];
                certificateFingerprint: string;
                changed: boolean;
            };
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
        } | {
            /** @constant */
            kind: "event";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** @description What the event is about — `build:<id>`, `instance:<id>`. Opaque. */
            subject: string;
            /** @constant */
            type: "sso.acs_changed";
            /** @description For a person (§14). Never parse it. */
            humanMessage: string;
            machineDetail: {
                from: string | null;
                to: string;
            };
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
        } | {
            /** @constant */
            kind: "event";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** @description What the event is about — `build:<id>`, `instance:<id>`. Opaque. */
            subject: string;
            /** @constant */
            type: "build.started";
            /** @description For a person (§14). Never parse it. */
            humanMessage: string;
            machineDetail: {
                /** Format: uuid */
                buildId: string;
                commitSha: string;
                blueprintRef: string;
            };
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
        } | {
            /** @constant */
            kind: "event";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** @description What the event is about — `build:<id>`, `instance:<id>`. Opaque. */
            subject: string;
            /** @constant */
            type: "build.succeeded";
            /** @description For a person (§14). Never parse it. */
            humanMessage: string;
            machineDetail: {
                /** Format: uuid */
                buildId: string;
                imageDigest: string | null;
                imageRepository: string | null;
            };
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
        } | {
            /** @constant */
            kind: "event";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** @description What the event is about — `build:<id>`, `instance:<id>`. Opaque. */
            subject: string;
            /** @constant */
            type: "build.failed";
            /** @description For a person (§14). Never parse it. */
            humanMessage: string;
            machineDetail: {
                /** Format: uuid */
                buildId: string;
                code: string | null;
                /** @description Redacted at capture (§14). For the agent; the human message is for a person. */
                reason: string;
            };
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
        } | {
            /** @constant */
            kind: "event";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** @description What the event is about — `build:<id>`, `instance:<id>`. Opaque. */
            subject: string;
            /** @constant */
            type: "instance.healthy";
            /** @description For a person (§14). Never parse it. */
            humanMessage: string;
            machineDetail: {
                /** Format: uuid */
                instanceId: string;
                /** Format: uuid */
                releaseId: string;
                /** Format: uuid */
                environmentId: string;
                /** @enum {string} */
                environment: "sandbox" | "staging" | "production";
                /** @enum {string} */
                state: "pending" | "building" | "provisioning" | "starting" | "healthy" | "failed" | "hibernated" | "waking" | "destroying" | "gone";
            };
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
        } | {
            /** @constant */
            kind: "event";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** @description What the event is about — `build:<id>`, `instance:<id>`. Opaque. */
            subject: string;
            /** @constant */
            type: "instance.failed";
            /** @description For a person (§14). Never parse it. */
            humanMessage: string;
            machineDetail: {
                /** Format: uuid */
                instanceId: string;
                /** Format: uuid */
                releaseId: string;
                /** Format: uuid */
                environmentId: string;
                /** @enum {string} */
                environment: "sandbox" | "staging" | "production";
                /** @enum {string} */
                state: "pending" | "building" | "provisioning" | "starting" | "healthy" | "failed" | "hibernated" | "waking" | "destroying" | "gone";
                failedCheck: string;
            };
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
        } | {
            /** @constant */
            kind: "event";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** @description What the event is about — `build:<id>`, `instance:<id>`. Opaque. */
            subject: string;
            /** @constant */
            type: "incident.opened";
            /** @description For a person (§14). Never parse it. */
            humanMessage: string;
            machineDetail: {
                /** Format: uuid */
                incidentId: string;
                /** Format: uuid */
                instanceId: string;
                /** Format: uuid */
                releaseId: string;
                /** @enum {string} */
                environment: "sandbox" | "staging" | "production";
            };
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
        } | {
            /** @constant */
            kind: "event";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** @description What the event is about — `build:<id>`, `instance:<id>`. Opaque. */
            subject: string;
            /** @constant */
            type: "ai.key_rotated";
            /** @description For a person (§14). Never parse it. */
            humanMessage: string;
            machineDetail: {
                /** Format: uuid */
                instanceId: string;
                /** @enum {string} */
                environment: "sandbox" | "staging" | "production";
                models: string[];
            };
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
        } | {
            /** @constant */
            kind: "event";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** @description What the event is about — `build:<id>`, `instance:<id>`. Opaque. */
            subject: string;
            /** @constant */
            type: "instance.retiring";
            /** @description For a person (§14). Never parse it. */
            humanMessage: string;
            machineDetail: {
                instanceId: string | null;
                handle: string;
                /** @enum {string} */
                environment: "sandbox" | "staging" | "production";
                drainMs: number;
            };
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
        } | {
            /** @constant */
            kind: "event";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** @description What the event is about — `build:<id>`, `instance:<id>`. Opaque. */
            subject: string;
            /** @constant */
            type: "instance.retired";
            /** @description For a person (§14). Never parse it. */
            humanMessage: string;
            machineDetail: {
                instanceId: string | null;
                handle: string;
                /** @enum {string} */
                environment: "sandbox" | "staging" | "production";
                drainMs: number;
            };
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
        } | {
            /** @constant */
            kind: "event";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** @description What the event is about — `build:<id>`, `instance:<id>`. Opaque. */
            subject: string;
            /** @constant */
            type: "instance.retire_failed";
            /** @description For a person (§14). Never parse it. */
            humanMessage: string;
            machineDetail: {
                instanceId: string | null;
                handle: string;
                /** @enum {string} */
                environment: "sandbox" | "staging" | "production";
                drainMs: number;
                /** @description A code or an error class name — never a message (§14). */
                error: string;
            };
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
        } | {
            /** @constant */
            kind: "event";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** @description What the event is about — `build:<id>`, `instance:<id>`. Opaque. */
            subject: string;
            /** @constant */
            type: "project.created";
            /** @description For a person (§14). Never parse it. */
            humanMessage: string;
            machineDetail: {
                slug: string;
                blueprint: string;
                starter: string | null;
                audience: {
                    /** @enum {string} */
                    scale: "solo" | "class" | "large_course" | "public";
                    /** @enum {string} */
                    burst: "steady" | "synchronised";
                };
            };
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
        } | {
            /** @constant */
            kind: "event";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** @description What the event is about — `build:<id>`, `instance:<id>`. Opaque. */
            subject: string;
            /** @constant */
            type: "repository.seeded";
            /** @description For a person (§14). Never parse it. */
            humanMessage: string;
            machineDetail: {
                commitSha: string;
                files: number;
                starter: string | null;
            };
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
        } | {
            /** @constant */
            kind: "event";
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** @description What the event is about — `build:<id>`, `instance:<id>`. Opaque. */
            subject: string;
            /** @constant */
            type: "spec.validated";
            /** @description For a person (§14). Never parse it. */
            humanMessage: string;
            machineDetail: {
                /** Format: uuid */
                appSpecId: string;
                commitSha: string;
                valid: boolean;
                errorCount: number;
            };
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
        };
        /** @description A running (or once-running) copy of a release in one environment (§11). Never its driver or handle. */
        Instance: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            environmentId: string;
            /** Format: uuid */
            releaseId: string;
            /** @enum {string} */
            kind: "web" | "worker" | "cron";
            /** @enum {string} */
            state: "pending" | "building" | "provisioning" | "starting" | "healthy" | "failed" | "hibernated" | "waking" | "destroying" | "gone";
            lastSeenAt: string | null;
        };
        /** @description D25: the files that teach an agent to write a valid manifest.yaml and wire the blueprint, versioned with it. */
        KnowledgePack: {
            blueprint: string;
            files: {
                path: string;
                /** @enum {string} */
                mediaType: "text/markdown" | "text/plain";
                /** @description Hex SHA-256 of `content` as UTF-8. */
                sha256: string;
                content: string;
            }[];
        };
        /** @description One line of a build’s output, as it is written. Never replayed — GET /v1/builds/{buildId}/logs has them all. */
        LogFrame: {
            /** @constant */
            kind: "log";
            /** @description `<buildId>:<seq>`. */
            id: string;
            /** Format: uuid */
            projectId: string;
            /** Format: uuid */
            buildId: string;
            seq: number;
            /** @enum {string} */
            stream: "stdout" | "stderr";
            /** @description Redacted at capture (§14). */
            text: string;
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
        };
        ManifestError: {
            code: components["schemas"]["ManifestErrorCode"];
            /** @description Where in manifest.yaml, dotted: `services.0.type`. */
            path: string;
            message: string;
            hint?: string;
        };
        /**
         * @description A code inside `details`: §7 schema, §7 policy, or §25 blueprint compatibility.
         * @enum {string}
         */
        ManifestErrorCode: "BLUEPRINT_AI_UNSUPPORTED" | "BLUEPRINT_AUTH_UNSUPPORTED" | "BLUEPRINT_SCHEMA_VERSION_UNSUPPORTED" | "BLUEPRINT_SERVICE_UNSUPPORTED" | "SPEC_AI_BUDGET_REQUIRED" | "SPEC_AI_DISABLED" | "SPEC_ATTRIBUTE_NOT_REGISTERED" | "SPEC_ATTRIBUTE_NOT_WHITELISTED" | "SPEC_BUILD_BLOCK_FORBIDDEN" | "SPEC_ENV_NAME_RESERVED" | "SPEC_INVALID_BLUEPRINT_REF" | "SPEC_INVALID_SLUG" | "SPEC_INVALID_VALUE" | "SPEC_MODEL_CLASSIFICATION_TOO_LOW" | "SPEC_MODEL_UNCLASSIFIED" | "SPEC_MODEL_UNKNOWN" | "SPEC_NAME_SLUG_MISMATCH" | "SPEC_PATH_EXPECTED" | "SPEC_QUOTA_EXCEEDED" | "SPEC_RESERVED_BLOCK_NOT_EMPTY" | "SPEC_SERVICE_TYPE_UNKNOWN" | "SPEC_UNKNOWN_KEY" | "SPEC_YAML_PARSE_FAILED";
        /** @description The person the session belongs to. */
        Me: {
            /** Format: uuid */
            id: string;
            /** @description The person's ubcEduCwlPuid (§9). */
            puid: string;
            displayName: string;
            email: string;
            /**
             * @description The platform role THIS SESSION is authorized as.
             * @enum {string}
             */
            role: "admin" | "member";
        };
        Member: {
            /** Format: uuid */
            userId: string;
            puid: string;
            displayName: string;
            email: string;
            /** @enum {string} */
            role: "owner" | "collaborator";
        };
        MemberList: components["schemas"]["Member"][];
        Project: {
            /** Format: uuid */
            id: string;
            /** @description The project’s name, and the first label of every hostname it has (§23). */
            slug: string;
            /** @description `name@major` (§25). */
            blueprint: string;
            /** @description The starter the first commit was seeded from (§25); null for the skeleton alone. */
            starter: string | null;
            owner: components["schemas"]["UserSummary"];
            audience: components["schemas"]["Audience"] | null;
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            createdAt: string;
            /** @description Present with `?expand=environments` (D23.1). */
            environments?: components["schemas"]["Environment"][];
        };
        ProjectList: components["schemas"]["Project"][];
        /** @description §12’s scan of the image a build produced (§6 `Build.scan`). */
        ScanSummary: {
            /** @description The scanner and its version — `fake` from the in-memory driver. */
            scanner: string;
            /**
             * Format: date-time
             * @description An instant, ISO 8601 in UTC.
             */
            scannedAt: string;
            /** @description How old the vulnerability database was, in days; null when the scanner could not say, and then `stale` is true. */
            databaseAgeDays: number | null;
            /** @description A clean result from a stale database is not evidence there is nothing to find (§12). */
            stale: boolean;
            /** @description False when the base image was not identified: every finding was attributed to the build, so `baseImage` counted nothing. */
            baseImageKnown: boolean;
            /** @description Introduced by this build, with a published fix. On a fresh database a build with any is refused (§12). */
            fixable: {
                critical: number;
                high: number;
            };
            /** @description Introduced by this build, with no published fix: recorded, not blocking (§12). */
            unfixable: {
                critical: number;
                high: number;
            };
            /** @description The base image’s own — the blueprint’s to fix (§20). */
            baseImage: {
                critical: number;
                high: number;
            };
            /** @description The unfixable findings by id, at most 50; `unfixable` counts them all. */
            unfixableFindings: {
                id: string;
                severity: string;
                package: string;
            }[];
        };
        /** @description D9. Reported, not yet enforced (P6). */
        SensitiveDiff: {
            sensitive: boolean;
            fields: string[];
        };
        /** @description §23: exactly what project creation will answer — advisory, since creation checks again. */
        SlugCheck: {
            slug: string;
            available: boolean;
            /** @description Present when `available` is false: every reason that applies. */
            reasons?: {
                /** @enum {string} */
                code: "SLUG_INVALID" | "SLUG_RESERVED" | "SLUG_TAKEN";
                message: string;
                hint: string;
            }[];
        };
        Spec: {
            /** Format: uuid */
            appSpecId: string;
            commitSha: string;
            /** @description manifest.yaml v1 as parsed and validated (§7). Its own JSON Schema is not published in P5a. */
            spec: {
                [key: string]: unknown;
            };
        };
        SpecValidation: {
            /** Format: uuid */
            appSpecId: string;
            commitSha: string;
            valid: boolean;
            errors: components["schemas"]["ManifestError"][];
            sensitiveDiff: components["schemas"]["SensitiveDiff"];
        };
        StartBuildRequest: {
            /** @description A full commit id. Defaults to the commit of the newest validated spec. */
            commitSha?: string;
        };
        /** @description Every message on WS /v1/projects/{projectId}/events is one of these, as JSON. Switch on `kind`, then `type`. */
        StreamFrame: components["schemas"]["EventFrame"] | components["schemas"]["LogFrame"] | components["schemas"]["ControlFrame"];
        UserSummary: {
            /** Format: uuid */
            id: string;
            displayName: string;
        };
        ValidateSpecRequest: {
            /** @description Defaults to the repository’s HEAD. */
            commitSha?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listBlueprints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every published blueprint. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlueprintList"];
                };
            };
            /** @description An error, in the D23.7 envelope. This operation can answer: INTERNAL, REQUEST_INVALID, UNAUTHENTICATED. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getBlueprint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blueprintRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The blueprint. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blueprint"];
                };
            };
            /** @description An error, in the D23.7 envelope. This operation can answer: INTERNAL, NOT_FOUND, REQUEST_INVALID, UNAUTHENTICATED. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getKnowledgePack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blueprintRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The pack. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgePack"];
                };
            };
            /** @description An error, in the D23.7 envelope. This operation can answer: INTERNAL, NOT_FOUND, REQUEST_INVALID, UNAUTHENTICATED. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getBuild: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                buildId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The build. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Build"];
                };
            };
            /** @description An error, in the D23.7 envelope. This operation can answer: INTERNAL, NOT_FOUND, REQUEST_INVALID, UNAUTHENTICATED. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getBuildLog: {
        parameters: {
            query?: {
                tail?: number;
            };
            header?: never;
            path: {
                buildId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The log. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildLog"];
                };
            };
            /** @description An error, in the D23.7 envelope. This operation can answer: INTERNAL, NOT_FOUND, REQUEST_INVALID, UNAUTHENTICATED. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                environmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The environment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"];
                };
            };
            /** @description An error, in the D23.7 envelope. This operation can answer: INTERNAL, NOT_FOUND, REQUEST_INVALID, UNAUTHENTICATED. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The person. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description An error, in the D23.7 envelope. This operation can answer: INTERNAL, REQUEST_INVALID, UNAUTHENTICATED. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller’s projects. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectList"];
                };
            };
            /** @description An error, in the D23.7 envelope. This operation can answer: INTERNAL, REQUEST_INVALID, UNAUTHENTICATED. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header: {
                /** @description D23.6. One per user action, reused across retries of THAT action. */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description The project, as created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedProject"];
                };
            };
            /** @description An error, in the D23.7 envelope. This operation can answer: AI_BACKEND_UNAVAILABLE, AI_CATALOGUE_EMPTY, BLUEPRINT_NOT_FOUND, CSRF_ORIGIN_REFUSED, IDEMPOTENCY_KEY_REQUIRED, IDEMPOTENCY_KEY_REUSED, INTERNAL, REQUEST_BODY_TOO_LARGE, REQUEST_INVALID, REQUEST_MEDIA_TYPE_UNSUPPORTED, SLUG_INVALID, SLUG_RESERVED, SLUG_TAKEN, SOURCE_GIT_FAILED, STARTER_NOT_FOUND, UNAUTHENTICATED. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: {
                expand?: "environments";
            };
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description An error, in the D23.7 envelope. This operation can answer: INTERNAL, NOT_FOUND, REQUEST_INVALID, UNAUTHENTICATED. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listBuilds: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The builds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildList"];
                };
            };
            /** @description An error, in the D23.7 envelope. This operation can answer: INTERNAL, NOT_FOUND, REQUEST_INVALID, UNAUTHENTICATED. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    startBuild: {
        parameters: {
            query?: never;
            header: {
                /** @description D23.6. One per user action, reused across retries of THAT action. */
                "Idempotency-Key": string;
            };
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartBuildRequest"];
            };
        };
        responses: {
            /** @description The build, started. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Build"];
                };
            };
            /** @description An error, in the D23.7 envelope. This operation can answer: BLUEPRINT_NOT_FOUND, CSRF_ORIGIN_REFUSED, FORBIDDEN, IDEMPOTENCY_KEY_REQUIRED, IDEMPOTENCY_KEY_REUSED, INTERNAL, NOT_FOUND, REQUEST_BODY_TOO_LARGE, REQUEST_INVALID, REQUEST_MEDIA_TYPE_UNSUPPORTED, SPEC_INVALID, SPEC_NOT_FOUND, UNAUTHENTICATED. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listEnvironments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The environments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvironmentList"];
                };
            };
            /** @description An error, in the D23.7 envelope. This operation can answer: INTERNAL, NOT_FOUND, REQUEST_INVALID, UNAUTHENTICATED. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    streamProjectEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Switching Protocols. Every message is one StreamFrame, as JSON. */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description This endpoint is a WebSocket; a plain GET is answered EVENTS_UPGRADE_REQUIRED. */
            426: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Refused before the upgrade, in the D23.7 envelope: UNAUTHENTICATED, NOT_FOUND (a stranger, or no such project), CSRF_ORIGIN_REFUSED, INTERNAL. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The members. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberList"];
                };
            };
            /** @description An error, in the D23.7 envelope. This operation can answer: INTERNAL, NOT_FOUND, REQUEST_INVALID, UNAUTHENTICATED. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    addMember: {
        parameters: {
            query?: never;
            header: {
                /** @description D23.6. One per user action, reused across retries of THAT action. */
                "Idempotency-Key": string;
            };
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            /** @description The member, as they now are. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            /** @description An error, in the D23.7 envelope. This operation can answer: CSRF_ORIGIN_REFUSED, FORBIDDEN, IDEMPOTENCY_KEY_REQUIRED, IDEMPOTENCY_KEY_REUSED, INTERNAL, MEMBER_USER_NOT_FOUND, NOT_FOUND, REQUEST_BODY_TOO_LARGE, REQUEST_INVALID, REQUEST_MEDIA_TYPE_UNSUPPORTED, UNAUTHENTICATED. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getSpec: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The spec. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Spec"];
                };
            };
            /** @description An error, in the D23.7 envelope. This operation can answer: INTERNAL, NOT_FOUND, REQUEST_INVALID, SPEC_INVALID, SPEC_NOT_FOUND, UNAUTHENTICATED. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    validateSpec: {
        parameters: {
            query?: never;
            header: {
                /** @description D23.6. One per user action, reused across retries of THAT action. */
                "Idempotency-Key": string;
            };
            path: {
                projectId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateSpecRequest"];
            };
        };
        responses: {
            /** @description The validation, valid or not — an invalid manifest is a recorded answer, not a refusal. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecValidation"];
                };
            };
            /** @description An error, in the D23.7 envelope. This operation can answer: AI_BACKEND_UNAVAILABLE, AI_CATALOGUE_EMPTY, CSRF_ORIGIN_REFUSED, FORBIDDEN, IDEMPOTENCY_KEY_REQUIRED, IDEMPOTENCY_KEY_REUSED, INTERNAL, NOT_FOUND, REQUEST_BODY_TOO_LARGE, REQUEST_INVALID, REQUEST_MEDIA_TYPE_UNSUPPORTED, SOURCE_GIT_FAILED, UNAUTHENTICATED. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    checkSlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The verdict. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlugCheck"];
                };
            };
            /** @description An error, in the D23.7 envelope. This operation can answer: INTERNAL, RATE_LIMITED, REQUEST_INVALID, UNAUTHENTICATED. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
